# NETWORK
bind 0.0.0.0
port 6379
protected-mode yes

# LOGGING
daemonize no
logfile ""
loglevel notice

# PERSISTENCE
dir /data
save 3600 1
save 300 100
save 60 10000
appendonly yes
appendfsync everysec

# MEMORY
maxmemory 100mb
maxmemory-policy allkeys-lru

# ACL USER
user default off
user superman on >superman ~* &* +@all
user habib on >pass123 resetchannels ~habib.* +@string +ping +del
